### ISSUE TITLE
week1day1 - 任务安排

### ISSUE THREAD

**Issue by absente** [restait/_collection#9]
时间：校历第二十周周二（7月11日 11:00）开始，最迟周三下午四点半验收。

# 任务

1.1 用自己的github账号，在这个issue下面回复任意内容。没有的去注册一个，以后常用到。
2.1 在自己的电脑上，下载并安装git，vscode
2.2 观看 https://www.typescriptlang.org/ 首页下的视频([备用链接](https://channel9.msdn.com/Events/Build/2017/B8088?ocid=player))，了解typescript的基础知识和vscode的基本用法
3. 通过github了解markdown格式的基本用法

## 可选
1.2 用学校邮箱申请github福利： https://education.github.com/
1.3 在自己的github账号下，新建一个repo，然后在里面写一篇issue，总结自己这一次的任务完成情况、收获、对typescript的理解或者前面那个视频的观后感（简短不用太长，如果觉得不好意思，可以用英文）
2.3 通过维基百科了解前面这个视频里面演讲者的相关背景（如果感兴趣的话）
2.4 如果觉得git命令行使用不顺手，可以考虑换成SourceTree
2.5 想搞前端的同学，可以先走下一步：确保自己电脑上有能用的Node.js
2.6 想搞Java后端的同学，可以先准备好 IntelliJ IDEA，安卓的准备好Android Studio
2.7 对Python感兴趣的同学，可以先安装Anaconda Python3，然后阅读这篇粗糙的[指南](http://www.jianshu.com/p/fd6ad8bb9e7f)

# 验收要求
会在11号晚上九点之前公布，不用太着急。

# 其他杂项
明天还会加你们的钉钉，组织结构统一用钉钉管理，然后用钉钉托管的worktile来分发今后的任务。这次的任务，之后会打补丁记上。分工分组确认预计周三晚上能够结束。

下东西网不好的，直接来实验楼0622，这里不断网。

## 备注

@absente 写道：

TypeScript在我看来，相对Python和Java而言，是一门更适合教学用的现代编程语言（该有的都有，不该有的历史包袱也可以不要）。所以无论你要搞前端还是后端，哪怕安卓，vscode这个编辑器，以及typescript的一些基础知识，如果自身觉得不是负担的话，我建议还是了解下。因为js本身用来搞大项目是很累的（如果你们有亲身体会的话），未来这种辅助类编程语言，我觉得多少会接触，包括JVM上的Kotlin，Google已经有打算在安卓用它逐步替代Java了，这跟苹果拿Swift接替Ojbective-C是一个道理。

相信应该有人在接触vscode之前可能也接触过sublime之类的编辑器，不过我们这里做一个规范，那就是统一用vscode作为最基本的文本编辑工具。至于后面前端后端各自的IDE，会另外安排。

另外，@myisjon  推荐了一个git教程给你们：

http://learngitbranching.js.org/

------
20170710 实验楼0622 -- init
20170711  -- fix order

**Comment by absente** [comment]
PS：虽然这次没有学分置换，优先级也不高，但还是希望有心学习的，自己多重视每一次的任务安排。

**Comment by zll0032** [comment]
信息六科

**Comment by Xavierhh** [comment]
Hail Hydra

**Comment by WingSpanCJ** [comment]
WingSpan李成杰

**Comment by Senor7620** [comment]
伊卡洛斯(ง •̀_•́)ง

**Comment by EliaTYN** [comment]
valar morghulis

**Comment by hamyct** [comment]
何炎圣

**Comment by zack1107** [comment]
资彬

**Comment by nwm1314** [comment]
聂文明

**Comment by Bguitarist** [comment]
邵艳祥

**Comment by absente** [comment]
准备close

**Comment by SilvioTao** [comment]
石韬

**Comment by 972751550** [comment]
李皓玮

**Comment by Cookie4kitty** [comment]
ddddd

**Comment by SiyZ** [comment]
张思阳

**Comment by SilvioTao** [comment]
习惯性去某乎看评论，在github找点小demo试试
https://github.com/SilvioTao/typescripe/issues/1

**Comment by ZhouJingtian** [comment]
周。。周靖添
